version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www/html/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - webnet
  php:
    build:
      context: ./php_pdo
    volumes:
      - ./project:/var/www/html/project
    networks:
      - webnet
networks:
  webnet: